<?php
session_start();
ob_start();

//--------------------------------------------------------------------------
// *** remote file inclusion, check for strange characters in $_GET keys
// *** all keys with "/", "\", ":" or "%-0-0" are blocked, so it becomes virtually impossible
// *** to inject other pages or websites
foreach($_GET as $get_key => $get_value) {
    if(is_string($get_value) && ((preg_match("/\//", $get_value)) || (preg_match("/\[\\\]/", $get_value)) || (preg_match("/:/", $get_value)) || (preg_match("/%00/", $get_value)))){
        if(isset($_GET[$get_key])) unset($_GET[$get_key]);
        die("A hacking attempt has been detected. For security reasons, we're blocking any code execution.");
    }
}

$uid = $_SESSION["txtId"];

include '../inc/config.inc.php';
include '../inc/function.inc.php';
$db = new Config(); 

$log = (isset($_REQUEST['log'])) ? "out" : "";
$msg = (isset($_REQUEST['msg'])) ? $_REQUEST['msg'] : "";

$adm_logged = (isset($_SESSION['adm_logged'])) ? $_SESSION['adm_logged'] : false;
if($adm_logged == true) {
	$left_menu_page = "left_menu.php";
	$content_page = "home.php";
} else {
	$left_menu_page = "left_menu_empty.php";
	$content_page = "login.php";
}
  
?>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3c.org/TR/1999/REC-html401-19991224/loose.dtd">
<html>
<head>
    <meta name="description" content="Website Back-End management script that provides access to the control features of your site." />
    <meta name="author" content="ApPHP Company">
    <meta name="generator" content="ApPHP AdminPanel">
    <title><?php echo _SITE_NAME?> :: Dashboard</title>
    <meta http-equiv=Content-Type content="text/html; charset=utf-8">

    <link href="../css/style_menu.css" type="text/css" rel="stylesheet">
    <link href="../css/pr-tools.css" type="text/css" rel="stylesheet">
    <link href="../css/style_<?php echo _CSS_STYLE?>.css" type=text/css rel=stylesheet>
    <link href="../bootstrap/css/bootstrap.min.css" type=text/css rel=stylesheet>
    <link href="../bootstrap/css/bootstrap-theme.min.min.css" type=text/css rel=stylesheet>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>


<?php include 'common/left_menu.php' ?>

<frameset rows="90px,*" FRAMEBORDER="no" FRAMESPACING="0" BORDER="0">
     <frame src="header.php" name="header" scrolling="no">
     <frameset cols="170px,*"  FRAMEBORDER="no" FRAMESPACING="0" BORDER="0">
          <frame src="<?php echo $left_menu_page; ?>" name="left_menu" scrolling="no">
          <frame src="<?php echo $content_page; ?>" name="frameMain">
     </frameset>
</frameset>
<!-- This script was generated by PHPAP (ApPHP AdminPanel) v1.0.5 | http://www.apphp.com/php-adminpanel/index.php -->
</html>

<script src="<?php echo _SITE_URL?>js/jquery-1.1.2.js" type="text/javascript"></script>
<script type="text/JavaScript" src="<?php echo _SITE_URL?>js/functions.js"></script>    
<script src="<?php echo _SITE_URL?>js/pr-tools.js" type="text/javascript"></script>
<script type="text/javaScript" src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script type="text/javaScript" src="<?php echo _SITE_URL?>bootstrap/js/bootstrap.min.js"></script>
<script type="text/javaScript" src="<?php echo _SITE_URL?>js/script_custom.js"></script>